# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wearehunted}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ggoodale"]
  s.date = %q{2010-03-30}
  s.description = %q{A Ruby wrapper around the We Are Hunted API.  See http://wearehunted.com/api for more information.}
  s.email = %q{ggoodale@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/wearehunted.rb",
     "test/fixtures/artist_shakira.json",
     "test/fixtures/artist_shakira_blog_post.json",
     "test/fixtures/artist_shakira_broken_bells.json",
     "test/fixtures/default_daily_singles_chart.json",
     "test/fixtures/default_daily_singles_chart_limited.json",
     "test/fixtures/jennifer_lopez_shakira_suggest.json",
     "test/fixtures/madonna_shakira_suggest.json",
     "test/fixtures/shakira_itunes_grooveshark.json",
     "test/fixtures/shakira_suggest.json",
     "test/fixtures/shakira_suggest_limited.json",
     "test/fixtures/twitter_daily_chart_itunes_grooveshark.json",
     "test/helper.rb",
     "test/test_wearehunted.rb",
     "wearehunted.gemspec"
  ]
  s.homepage = %q{http://github.com/ggoodale/wearehunted}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Ruby wrapper around the We Are Hunted API.}
  s.test_files = [
    "test/helper.rb",
     "test/test_wearehunted.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

